### ISSUE TITLE
Will 7.1.1 be supported?

### ISSUE THREAD

**Issue by zazahunter** [nasosi/C4EngineExamples#3]
Hi,

It seems like latest version wont compile, so will 7.1.1 ever be supported?
![image](https://github.com/nasosi/C4EngineExamples/assets/140970127/d279444b-52cd-4350-b090-fb7a25c6d3a5)

**Comment by nasosi** [comment]
@zazahunter, I compiled everything with 7.1.1 and also with the current C4 origin/main, and I am not getting this error. Regardless, I uploaded a patch to comply with the new way the debug and optimized defines work in C4 now, so you may want to try it. 

For this test, I used the following Cmake configuration in Visual Studio 2022. Notice that I placed the C4-Engine code, the C4-Data-7.1.1, and C4EngineExamples in separate directories under ```tmp```.

<img width="809" alt="image" src="https://github.com/nasosi/C4EngineExamples/assets/2938701/e4067b7b-61cb-4885-bee5-edb0cd7a6a35">

Notice also what the startup item should be:
<img width="289" alt="image" src="https://github.com/nasosi/C4EngineExamples/assets/2938701/901f548b-b998-4b7c-9c60-8ba32e07c2e1">

There is a chance that you may want to compile twice if one of the plugins ```dll```s is not found. This is a known compile order issue that sporadically manifests that I haven't had the chance to resolve yet.

What IDE/compiler are you using?

Thanks!

**Comment by zazahunter** [comment]
Hi,
I will check this out tomorrow thanks for the response!

**Comment by zazahunter** [comment]
Hey,

I just tested it now instead and found out it was a issue on my side and nothing to do with your project.
