### ISSUE TITLE
How do i disable TERATHON_NO_SYSTEM

### ISSUE THREAD

**Issue by CitroenGames** [nasosi/C4EngineExamples#3]
Hi,

I tried disabling TERATHON_NO_SYSTEM by removing it at line 217 inside of cmake/EngineCode/CMakeLists.txt 
but after compiling I get a few error's.

(this was done on a fresh install this could be a c4 related issue.)

![image](https://github.com/nasosi/C4EngineExamples/assets/54474809/ee81f5aa-bfcf-40a8-a57b-1fffa7e8a1f5)

**Comment by nasosi** [comment]
Hey @CitroenGames,

You need to remove ```TERATHON_NO_SYSTEM``` from ```cmake/EngineCode/CMakeLists.txt``` line 214:
https://github.com/nasosi/C4EngineExamples/blob/b041162591e0c1359b7c92ae9c6a4796df479672/cmake/EngineCode/CMakeLists.txt#L214

, but also from line 16 in ```cmake/cmake_macros/c4functions.cmake```:

https://github.com/nasosi/C4EngineExamples/blob/b041162591e0c1359b7c92ae9c6a4796df479672/cmake/cmake_macros/c4functions.cmake#L16

But, if you only need this for your game (i.e., you don't plan to modify the C4Engine code in a manner that requires using standard C++ facilities), then you can remove the define only for your game.

This is done in example ```010_node_iterator```. Compare its ```CMake``` ```target_compile_definitions```:

https://github.com/nasosi/C4EngineExamples/blob/b041162591e0c1359b7c92ae9c6a4796df479672/src/010_node_iterator/CMakeLists.txt#L31)

, with the relevant line in any other example, like ```009_custom_controller```:

https://github.com/nasosi/C4EngineExamples/blob/b041162591e0c1359b7c92ae9c6a4796df479672/src/009_custom_controller/CMakeLists.txt#L31

I am currently working on substantial changes in the ```C4EngineExamples``` build configuration and will include this as an option.

**Comment by CitroenGames** [comment]
Hi,

Thanks for this information and i will try it right now.

**Comment by CitroenGames** [comment]
After trying a few things i wasnt able to include anything from the std library.

Removing TERATHON_NO_SYSTEM does compile successfully but if i do any include from std library I receive telling me that new and delete is already defined.
![image](https://github.com/nasosi/C4EngineExamples/assets/54474809/609d3940-b061-4801-9992-3cd613c40387)

**Comment by nasosi** [comment]
Hello,

I pushed a test branch with TERATHON_NO_SYSTEM removed from the compile definitions of 001_simple, and some random ```std::vector``` and ```std::string``` includes and code. I cannot reproduce the error. It also works even after removing TERATHON_NO_SYSTEM from the Engine and the Plugins locations.

Can you try to checkout the branch?
https://github.com/nasosi/C4EngineExamples/tree/TestTerathonNoSystem

Here are the relevant changes.
https://github.com/nasosi/C4EngineExamples/commit/8fa4d4e52b0306180c629532fe37c8dafb1ccd18

Something else you may want to try is to perform a full rebuild, or even remove the ```out``` directory generated by Visual Studio in the local build folder. Sometimes ninja doesn't pick up all the changes and may not recompile when it should.

If you can describe the steps you took that resulted in this error in more detail, I will try to reproduce it.

**Comment by CitroenGames** [comment]
Hi.

I will test it right now.

**Comment by CitroenGames** [comment]
After testing that branch i realized that I need to clean up the build folder after I changed the pre-processor inside of cmake.

So in other words it works now!
